//
//  TermsView.swift
//  Voltaire
//

import SwiftUI

struct TermsView: View {
    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 20) {
                Text("Terms and Conditions")
                    .font(.title2.weight(.semibold))
                
                Text("Last updated: July 5, 2026")
                    .font(.footnote)
                    .foregroundStyle(.secondary)
                
                Group {
                    section("1. Acceptance of Terms", content: """
                    By downloading, installing, or using Voltaire (\"the App\"), you agree to be bound by these Terms and Conditions. If you do not agree to these terms, do not use the App.
                    """)
                    
                    section("2. Description of Service", content: """
                    Voltaire is an on-device AI chat application that runs large language models locally on your device. The App does not transmit your conversations or personal data to external servers. All processing occurs locally on your device.
                    """)
                    
                    section("3. User Responsibilities", content: """
                    You are responsible for:
                    - Ensuring your device meets the minimum requirements to run the App
                    - Managing the storage space required for downloaded models
                    - The content of your prompts and conversations with AI models
                    - Using the App in compliance with all applicable laws and regulations
                    """)
                    
                    section("4. AI-Generated Content", content: """
                    Content generated by AI models within the App is provided \"as is\" without any guarantees of accuracy, completeness, or reliability. You should not rely on AI-generated content as professional advice (medical, legal, financial, or otherwise). The developers of Voltaire are not responsible for any decisions made based on AI-generated content.
                    """)
                    
                    section("5. Model Downloads", content: """
                    The App allows you to download open-source AI models from Hugging Face. These models are subject to their own respective licenses and terms of service. By downloading a model, you agree to comply with its license terms. The App does not host or distribute models; it facilitates downloads from third-party sources.
                    """)
                    
                    section("6. Intellectual Property", content: """
                    The App, including its design, interface, and original code, is the intellectual property of its developers. Open-source libraries used in the App are subject to their respective licenses (primarily MIT License). Model weights are the property of their respective creators and are distributed under open-source licenses.
                    """)
                    
                    section("7. Limitation of Liability", content: """
                    To the maximum extent permitted by applicable law, the developers of Voltaire shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from:
                    - Your use of or inability to use the App
                    - Any conduct or content of any third party related to the App
                    - Any content obtained from the App
                    - Unauthorized access, use, or alteration of your transmissions or content
                    """)
                    
                    section("8. No Warranty", content: """
                    The App is provided \"as is\" and \"as available\" without warranties of any kind, whether express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, and non-infringement.
                    """)
                    
                    section("9. Changes to Terms", content: """
                    We reserve the right to modify these Terms and Conditions at any time. Changes will be effective immediately upon posting. Your continued use of the App after any changes constitutes acceptance of the new terms.
                    """)
                    
                    section("10. Contact", content: """
                    If you have any questions about these Terms and Conditions, please contact us through the App's support channels.
                    """)
                }
            }
            .padding()
        }
        .modifier(CustomNavTitle(title: "Terms & Conditions"))
        .navigationPopGestureDisabled(true)
        .navigationBarTitleDisplayMode(.inline)
    }
    
    private func section(_ title: String, content: String) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            Text(title)
                .font(.headline)
            Text(content)
                .font(.body)
                .foregroundStyle(.secondary)
        }
    }
}

#Preview {
    TermsView()
}
