export default function Terms() {
  return (
    <main className="legal-page">
      <div className="container">
        <a href="/" className="back-link"><i className="fa-solid fa-arrow-left"></i> Back to home</a>
        <h1>Terms and Conditions</h1>
        <p className="legal-updated">Last updated: July 5, 2026</p>

        <div className="legal-section">
          <h3>1. Acceptance of Terms</h3>
          <p>By downloading, installing, or using Voltaire (&quot;the App&quot;), you agree to be bound by these Terms and Conditions. If you do not agree to these terms, do not use the App.</p>
        </div>

        <div className="legal-section">
          <h3>2. Description of Service</h3>
          <p>Voltaire is an on-device AI chat application that runs large language models locally on your device. The App does not transmit your conversations or personal data to external servers. All processing occurs locally on your device.</p>
        </div>

        <div className="legal-section">
          <h3>3. User Responsibilities</h3>
          <p>You are responsible for:</p>
          <ul>
            <li>Ensuring your device meets the minimum requirements to run the App</li>
            <li>Managing the storage space required for downloaded models</li>
            <li>The content of your prompts and conversations with AI models</li>
            <li>Using the App in compliance with all applicable laws and regulations</li>
          </ul>
        </div>

        <div className="legal-section">
          <h3>4. AI-Generated Content</h3>
          <p>Content generated by AI models within the App is provided &quot;as is&quot; without any guarantees of accuracy, completeness, or reliability. You should not rely on AI-generated content as professional advice (medical, legal, financial, or otherwise). The developers of Voltaire are not responsible for any decisions made based on AI-generated content.</p>
        </div>

        <div className="legal-section">
          <h3>5. Model Downloads</h3>
          <p>The App allows you to download open-source AI models from Hugging Face. These models are subject to their own respective licenses and terms of service. By downloading a model, you agree to comply with its license terms. The App does not host or distribute models; it facilitates downloads from third-party sources.</p>
        </div>

        <div className="legal-section">
          <h3>6. Intellectual Property</h3>
          <p>The App, including its design, interface, and original code, is the intellectual property of its developers. Open-source libraries used in the App are subject to their respective licenses (primarily MIT License). Model weights are the property of their respective creators and are distributed under open-source licenses.</p>
        </div>

        <div className="legal-section">
          <h3>7. Limitation of Liability</h3>
          <p>To the maximum extent permitted by applicable law, the developers of Voltaire shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from:</p>
          <ul>
            <li>Your use of or inability to use the App</li>
            <li>Any conduct or content of any third party related to the App</li>
            <li>Any content obtained from the App</li>
            <li>Unauthorized access, use, or alteration of your transmissions or content</li>
          </ul>
        </div>

        <div className="legal-section">
          <h3>8. No Warranty</h3>
          <p>The App is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, whether express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, and non-infringement.</p>
        </div>

        <div className="legal-section">
          <h3>9. Changes to Terms</h3>
          <p>We reserve the right to modify these Terms and Conditions at any time. Changes will be effective immediately upon posting. Your continued use of the App after any changes constitutes acceptance of the new terms.</p>
        </div>

        <div className="legal-section">
          <h3>10. Contact</h3>
          <p>If you have any questions about these Terms and Conditions, please contact us through the App&apos;s support channels.</p>
        </div>
      </div>
    </main>
  );
}
